#pragma once

#include <cstddef>
#include <cstdint>
#include <limits>
#include <stdexcept>
#include <utility>

#include "emmus/memory/identifiers/MemoryObjectIds.hpp"

namespace emmus::memory::access {

/**
 * @brief Strongly typed virtual-memory address.
 *
 * A VirtualAddress represents an address generated by a simulated process.
 *
 * The MMU decomposes the address into:
 *
 *     Virtual Page + Page Offset
 *
 * The page size used for that decomposition is supplied by the MMU.
 */
class VirtualAddress final {
public:
    using ValueType = std::uint64_t;

    constexpr explicit VirtualAddress(ValueType value) noexcept
        : value_(value) {}

    [[nodiscard]] constexpr ValueType value() const noexcept {
        return value_;
    }

    [[nodiscard]] constexpr bool operator==(const VirtualAddress&) const noexcept = default;

    [[nodiscard]] constexpr bool operator!=(const VirtualAddress&) const noexcept = default;

private:
    ValueType value_;
};

/**
 * @brief Strongly typed physical-memory address.
 *
 * A PhysicalAddress represents the translated physical address.
 *
 * It is composed conceptually of:
 *
 *     Physical Frame + Page Offset
 */
class PhysicalAddress final {
public:
    using ValueType = std::uint64_t;

    constexpr explicit PhysicalAddress(ValueType value) noexcept
        : value_(value) {}

    [[nodiscard]] constexpr ValueType value() const noexcept {
        return value_;
    }

    [[nodiscard]] constexpr bool operator==(const PhysicalAddress&) const noexcept = default;

    [[nodiscard]] constexpr bool operator!=(const PhysicalAddress&) const noexcept = default;

private:
    ValueType value_;
};

/**
 * @brief Strongly typed page offset.
 *
 * The offset identifies a byte within a page and remains unchanged during
 * virtual-to-physical address translation.
 */
class PageOffset final {
public:
    using ValueType = std::uint64_t;

    constexpr explicit PageOffset(ValueType value) noexcept
        : value_(value) {}

    [[nodiscard]] constexpr ValueType value() const noexcept {
        return value_;
    }

    [[nodiscard]] constexpr bool operator==(const PageOffset&) const noexcept = default;

    [[nodiscard]] constexpr bool operator!=(const PageOffset&) const noexcept = default;

private:
    ValueType value_;
};

/**
 * @brief Strongly typed page size, expressed in bytes.
 */
class PageSize final {
public:
    using ValueType = std::uint64_t;

    /**
     * @brief Constructs a page size.
     *
     * A page size must be greater than zero.
     */
    explicit constexpr PageSize(ValueType value)
        : value_(value) {
        if (value == 0) {
            throw std::invalid_argument("Page size must be greater than zero");
        }
    }

    [[nodiscard]] constexpr ValueType value() const noexcept {
        return value_;
    }

    [[nodiscard]] constexpr bool operator==(const PageSize&) const noexcept = default;

    [[nodiscard]] constexpr bool operator!=(const PageSize&) const noexcept = default;

private:
    ValueType value_;
};

/**
 * @brief Strongly typed physical-frame count.
 */
class FrameCount final {
public:
    using ValueType = std::size_t;

    /**
     * @brief Constructs a frame count.
     *
     * A physical-memory configuration must contain at least one frame.
     */
    explicit constexpr FrameCount(ValueType value)
        : value_(value) {
        if (value == 0) {
            throw std::invalid_argument(
                "Physical memory must contain at least one frame");
        }
    }

    [[nodiscard]] constexpr ValueType value() const noexcept {
        return value_;
    }

    [[nodiscard]] constexpr bool operator==(const FrameCount&) const noexcept = default;

    [[nodiscard]] constexpr bool operator!=(const FrameCount&) const noexcept = default;

private:
    ValueType value_;
};

/**
 * @brief Strongly typed memory-access sequence number.
 *
 * Sequence numbers provide deterministic access ordering and are useful
 * to the Optimal replacement policy.
 */
class AccessSequenceNumber final {
public:
    using ValueType = std::uint64_t;

    constexpr explicit AccessSequenceNumber(ValueType value) noexcept
        : value_(value) {}

    [[nodiscard]] constexpr ValueType value() const noexcept {
        return value_;
    }

    [[nodiscard]] constexpr bool operator==(const AccessSequenceNumber&) const noexcept = default;

    [[nodiscard]] constexpr bool operator!=(const AccessSequenceNumber&) const noexcept = default;

private:
    ValueType value_;
};

/**
 * @brief Decomposes a virtual address into its virtual-page number and offset.
 *
 * The address model is:
 *
 *     Virtual Address = Virtual Page * Page Size + Page Offset
 *
 * This function intentionally performs the calculation without imposing a
 * particular address-width policy beyond the uint64_t representation.
 *
 * @param address Virtual address to decompose.
 * @param pageSize Configured page size in bytes.
 *
 * @return Pair containing:
 *         - PageId
 *         - PageOffset
 */
[[nodiscard]] constexpr auto decomposeVirtualAddress(
    VirtualAddress address,
    PageSize pageSize)
    -> std::pair<emmus::memory::identifiers::PageId, PageOffset> {
    const auto pageSizeValue = pageSize.value();
    const auto addressValue = address.value();

    const auto pageNumber = addressValue / pageSizeValue;
    const auto offset = addressValue % pageSizeValue;

    return {
        emmus::memory::identifiers::PageId{pageNumber},
        PageOffset{offset}
    };
}

/**
 * @brief Constructs a physical address from a frame and page offset.
 *
 * The physical address is:
 *
 *     Physical Address = Frame ID * Page Size + Page Offset
 *
 * @param frameId Physical frame containing the page.
 * @param offset Offset within the page.
 * @param pageSize Configured page size in bytes.
 *
 * @return Translated physical address.
 *
 * @throws std::overflow_error if the resulting address cannot be represented
 *         by the PhysicalAddress value type.
 */
[[nodiscard]] constexpr PhysicalAddress makePhysicalAddress(
    emmus::memory::identifiers::FrameId frameId,
    PageOffset offset,
    PageSize pageSize) {
    using ValueType = PhysicalAddress::ValueType;

    const ValueType frameValue = frameId.value();
    const ValueType pageSizeValue = pageSize.value();
    const ValueType offsetValue = offset.value();

    constexpr ValueType maxValue = std::numeric_limits<ValueType>::max();

    if (frameValue > (maxValue - offsetValue) / pageSizeValue) {
        throw std::overflow_error(
            "Physical address exceeds the supported address range");
    }

    return PhysicalAddress{
        frameValue * pageSizeValue + offsetValue
    };
}

}  // namespace emmus::memory::access